name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set docker image version'
        required: true
        type: string
jobs:

  build_image:
    name: Build docker image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag javabeans/sprintpoker:${{ inputs.version }}
    - if: success()
    - uses: manusa/actions-publish-docker@v1.1.21
    - with:
        name: javabeans/sprintpoker:${{ inputs.version }}
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
